# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci = [1, 2]

def find_fibonacci
  i = 0
  while fibonacci[i] <= 4000000
    fibonacci << (fibonacci[i] + fibonacci[i+1])
    i += 1
  end
end

sum = 0

def sum_of_evens
  fibonacci.each do |fib|
    if fib.even?
      sum += fib
    end
  end
end